use_frameworks!

platform :ios, '10.0'

target 'LottieService_Example' do
  pod 'LottieService', :path => '../'

  target 'LottieService_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
